# Generated by Django 6.0.5 on 2026-05-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('friends', models.ManyToManyField(blank=True, to='charlotte.user')),
                ('groups', models.ManyToManyField(blank=True, to='charlotte.user')),
            ],
        ),
    ]
